
obj-$(CONFIG_AML_BL_EXTERN)			+= bl_extern.o bl_extern_i2c_dev.o
obj-$(CONFIG_AML_BL_EXTERN_I2C_LP8556)		+= i2c_lp8556.o
obj-$(CONFIG_AML_BL_EXTERN_MIPI_IT070ME05)	+= mipi_lt070me05.o
obj-$(CONFIG_AML_BL_EXTERN_I2C_M0516LDN)	+= i2c_m0516ldn.o
obj-$(CONFIG_AML_SEDES)				+= i2c_serdes_0.o
obj-$(CONFIG_AML_SEDES)				+= i2c_serdes_1.o
obj-$(CONFIG_AML_BL_EXTERN_I2C_A8552)		+= i2c_a8552.o