obj-$(CONFIG_AMAZON_METRICS_LOG)	+= amazon_logger.o
obj-$(CONFIG_AMAZON_METRICS_LOG_TEST)	+= amazon_logger_test.o
obj-$(CONFIG_AMAZON_SIGN_OF_LIFE)	+= sign_of_life.o sign_of_life_vendor.o
obj-$(CONFIG_AMAZON_SOC_STATE_PWM)	+= soc_state_pwm.o